export type Food = { name: string; cal: number; unit: string; cat: string };

export const FOODS: Food[] = [
  // 밥류
  { name: "쌀밥", cal: 290, unit: "공기(200g)", cat: "밥류" },
  { name: "현미밥", cal: 280, unit: "공기(200g)", cat: "밥류" },
  { name: "잡곡밥", cal: 270, unit: "공기(200g)", cat: "밥류" },
  { name: "비빔밥", cal: 560, unit: "1인분", cat: "밥류" },
  { name: "볶음밥", cal: 520, unit: "1인분", cat: "밥류" },
  { name: "오므라이스", cal: 520, unit: "1인분", cat: "밥류" },
  { name: "김밥", cal: 350, unit: "1줄", cat: "밥류" },
  { name: "참치김밥", cal: 380, unit: "1줄", cat: "밥류" },
  { name: "삼각김밥(참치마요)", cal: 180, unit: "1개", cat: "밥류" },
  { name: "삼각김밥(김치)", cal: 150, unit: "1개", cat: "밥류" },
  { name: "유부초밥", cal: 380, unit: "1인분(8개)", cat: "밥류" },
  // 면류
  { name: "라면", cal: 420, unit: "1인분", cat: "면류" },
  { name: "컵라면(신라면)", cal: 310, unit: "1개", cat: "면류" },
  { name: "짜장면", cal: 600, unit: "1인분", cat: "면류" },
  { name: "짬뽕", cal: 550, unit: "1인분", cat: "면류" },
  { name: "냉면", cal: 450, unit: "1인분", cat: "면류" },
  { name: "비빔냉면", cal: 550, unit: "1인분", cat: "면류" },
  { name: "칼국수", cal: 430, unit: "1인분", cat: "면류" },
  { name: "우동", cal: 400, unit: "1인분", cat: "면류" },
  { name: "파스타(크림)", cal: 620, unit: "1인분", cat: "면류" },
  { name: "파스타(토마토)", cal: 480, unit: "1인분", cat: "면류" },
  { name: "스파게티", cal: 500, unit: "1인분", cat: "면류" },
  // 분식
  { name: "떡볶이", cal: 380, unit: "1인분", cat: "분식" },
  { name: "순대", cal: 280, unit: "1인분", cat: "분식" },
  { name: "튀김", cal: 320, unit: "1인분", cat: "분식" },
  { name: "어묵(꼬치)", cal: 80, unit: "1개", cat: "분식" },
  { name: "붕어빵", cal: 150, unit: "1개", cat: "분식" },
  { name: "호떡", cal: 230, unit: "1개", cat: "분식" },
  { name: "핫도그", cal: 280, unit: "1개", cat: "분식" },
  { name: "소떡소떡", cal: 320, unit: "1인분(2개)", cat: "분식" },
  { name: "핫바", cal: 180, unit: "1개", cat: "분식" },
  // 국/찌개
  { name: "김치찌개", cal: 120, unit: "1인분", cat: "국/찌개" },
  { name: "된장찌개", cal: 130, unit: "1인분", cat: "국/찌개" },
  { name: "순두부찌개", cal: 180, unit: "1인분", cat: "국/찌개" },
  { name: "부대찌개", cal: 350, unit: "1인분", cat: "국/찌개" },
  { name: "미역국", cal: 60, unit: "1인분", cat: "국/찌개" },
  { name: "콩나물국", cal: 40, unit: "1인분", cat: "국/찌개" },
  { name: "육개장", cal: 180, unit: "1인분", cat: "국/찌개" },
  { name: "갈비탕", cal: 270, unit: "1인분", cat: "국/찌개" },
  { name: "해장국", cal: 220, unit: "1인분", cat: "국/찌개" },
  { name: "감자탕", cal: 380, unit: "1인분", cat: "국/찌개" },
  { name: "설렁탕", cal: 300, unit: "1인분", cat: "국/찌개" },
  { name: "순대국밥", cal: 450, unit: "1인분", cat: "국/찌개" },
  // 고기구이
  { name: "삼겹살", cal: 331, unit: "100g", cat: "고기" },
  { name: "목살", cal: 180, unit: "100g", cat: "고기" },
  { name: "갈비", cal: 300, unit: "100g", cat: "고기" },
  { name: "불고기", cal: 200, unit: "100g", cat: "고기" },
  { name: "제육볶음", cal: 350, unit: "1인분", cat: "고기" },
  { name: "닭가슴살", cal: 165, unit: "100g", cat: "고기" },
  { name: "닭다리(구이)", cal: 180, unit: "100g", cat: "고기" },
  { name: "닭갈비", cal: 380, unit: "1인분", cat: "고기" },
  { name: "오리고기", cal: 337, unit: "100g", cat: "고기" },
  { name: "소갈비찜", cal: 340, unit: "1인분", cat: "고기" },
  { name: "돼지갈비", cal: 310, unit: "1인분(200g)", cat: "고기" },
  // 치킨/패스트푸드
  { name: "후라이드치킨", cal: 850, unit: "1인분(반마리)", cat: "치킨/패스트푸드" },
  { name: "양념치킨", cal: 950, unit: "1인분(반마리)", cat: "치킨/패스트푸드" },
  { name: "치킨(조각)", cal: 250, unit: "1조각(100g)", cat: "치킨/패스트푸드" },
  { name: "빅맥", cal: 550, unit: "1개", cat: "치킨/패스트푸드" },
  { name: "불고기버거", cal: 430, unit: "1개", cat: "치킨/패스트푸드" },
  { name: "치킨버거", cal: 420, unit: "1개", cat: "치킨/패스트푸드" },
  { name: "감자튀김(M)", cal: 320, unit: "1개", cat: "치킨/패스트푸드" },
  { name: "감자튀김(L)", cal: 440, unit: "1개", cat: "치킨/패스트푸드" },
  { name: "치킨너겟(6개)", cal: 270, unit: "6개", cat: "치킨/패스트푸드" },
  { name: "피자(치즈, 1조각)", cal: 280, unit: "1조각", cat: "치킨/패스트푸드" },
  { name: "피자(페퍼로니, 1조각)", cal: 320, unit: "1조각", cat: "치킨/패스트푸드" },
  // 배달음식
  { name: "족발", cal: 280, unit: "100g", cat: "배달" },
  { name: "보쌈", cal: 240, unit: "100g", cat: "배달" },
  { name: "탕수육", cal: 380, unit: "1인분", cat: "배달" },
  { name: "마라탕", cal: 450, unit: "1인분", cat: "배달" },
  { name: "마라샹궈", cal: 600, unit: "1인분", cat: "배달" },
  { name: "국밥", cal: 450, unit: "1인분", cat: "배달" },
  { name: "떡볶이(배달)", cal: 400, unit: "1인분", cat: "배달" },
  // 계란/두부
  { name: "계란후라이", cal: 95, unit: "1개", cat: "계란/두부" },
  { name: "계란말이", cal: 150, unit: "1인분(계란2개)", cat: "계란/두부" },
  { name: "계란찜", cal: 130, unit: "1인분", cat: "계란/두부" },
  { name: "삶은달걀", cal: 80, unit: "1개", cat: "계란/두부" },
  { name: "두부조림", cal: 120, unit: "1인분", cat: "계란/두부" },
  { name: "순두부", cal: 60, unit: "100g", cat: "계란/두부" },
  { name: "두부(구이)", cal: 90, unit: "100g", cat: "계란/두부" },
  // 생선/해산물
  { name: "고등어구이", cal: 160, unit: "1토막", cat: "생선/해산물" },
  { name: "갈치구이", cal: 140, unit: "1토막", cat: "생선/해산물" },
  { name: "연어구이", cal: 200, unit: "100g", cat: "생선/해산물" },
  { name: "참치캔", cal: 180, unit: "1캔(100g)", cat: "생선/해산물" },
  { name: "오징어볶음", cal: 200, unit: "1인분", cat: "생선/해산물" },
  { name: "새우볶음", cal: 150, unit: "1인분", cat: "생선/해산물" },
  { name: "어묵", cal: 100, unit: "100g", cat: "생선/해산물" },
  { name: "꽃게찜", cal: 90, unit: "100g", cat: "생선/해산물" },
  // 반찬
  { name: "김치", cal: 15, unit: "100g", cat: "반찬" },
  { name: "깍두기", cal: 20, unit: "100g", cat: "반찬" },
  { name: "시금치나물", cal: 25, unit: "1인분", cat: "반찬" },
  { name: "콩나물무침", cal: 30, unit: "1인분", cat: "반찬" },
  { name: "멸치볶음", cal: 80, unit: "1인분", cat: "반찬" },
  { name: "조림감자", cal: 110, unit: "1인분", cat: "반찬" },
  { name: "잡채", cal: 300, unit: "1인분", cat: "반찬" },
  { name: "해물파전", cal: 350, unit: "1인분", cat: "반찬" },
  { name: "김(구이)", cal: 20, unit: "1장", cat: "반찬" },
  // 편의점
  { name: "편의점 도시락", cal: 550, unit: "1개", cat: "편의점" },
  { name: "편의점 샌드위치", cal: 280, unit: "1개", cat: "편의점" },
  { name: "바나나우유", cal: 160, unit: "240ml", cat: "편의점" },
  { name: "요구르트(떠먹는)", cal: 140, unit: "1개(150g)", cat: "편의점" },
  { name: "크림빵", cal: 350, unit: "1개", cat: "편의점" },
  // 음료/커피
  { name: "아메리카노", cal: 10, unit: "1잔(톨)", cat: "음료/커피" },
  { name: "카페라떼", cal: 120, unit: "1잔(톨)", cat: "음료/커피" },
  { name: "카푸치노", cal: 110, unit: "1잔(톨)", cat: "음료/커피" },
  { name: "카라멜마키아토", cal: 250, unit: "1잔(톨)", cat: "음료/커피" },
  { name: "초코라떼", cal: 300, unit: "1잔(톨)", cat: "음료/커피" },
  { name: "아이스크림라떼", cal: 380, unit: "1잔", cat: "음료/커피" },
  { name: "콜라", cal: 140, unit: "350ml", cat: "음료/커피" },
  { name: "사이다", cal: 130, unit: "350ml", cat: "음료/커피" },
  { name: "오렌지주스", cal: 110, unit: "200ml", cat: "음료/커피" },
  { name: "이온음료(포카리 등)", cal: 70, unit: "500ml", cat: "음료/커피" },
  { name: "에너지드링크", cal: 100, unit: "250ml", cat: "음료/커피" },
  { name: "맥주", cal: 145, unit: "1캔(355ml)", cat: "음료/커피" },
  { name: "소주", cal: 300, unit: "1병(360ml)", cat: "음료/커피" },
  { name: "막걸리", cal: 200, unit: "1병(750ml)", cat: "음료/커피" },
  { name: "두유", cal: 130, unit: "190ml", cat: "음료/커피" },
  { name: "녹차", cal: 0, unit: "1잔", cat: "음료/커피" },
  { name: "홍차(무가당)", cal: 5, unit: "1잔", cat: "음료/커피" },
  // 빵/베이커리
  { name: "식빵", cal: 250, unit: "2쪽(100g)", cat: "빵" },
  { name: "크루아상", cal: 300, unit: "1개(70g)", cat: "빵" },
  { name: "바게트", cal: 280, unit: "100g", cat: "빵" },
  { name: "단팥빵", cal: 280, unit: "1개", cat: "빵" },
  { name: "소보로빵", cal: 320, unit: "1개", cat: "빵" },
  { name: "치즈케이크", cal: 380, unit: "1조각(100g)", cat: "빵" },
  { name: "초코케이크", cal: 420, unit: "1조각(100g)", cat: "빵" },
  { name: "도넛", cal: 250, unit: "1개", cat: "빵" },
  { name: "와플", cal: 290, unit: "1개", cat: "빵" },
  { name: "마카롱", cal: 100, unit: "1개", cat: "빵" },
  // 과일
  { name: "사과", cal: 80, unit: "1개(250g)", cat: "과일" },
  { name: "바나나", cal: 90, unit: "1개(100g)", cat: "과일" },
  { name: "오렌지", cal: 60, unit: "1개(200g)", cat: "과일" },
  { name: "포도", cal: 70, unit: "100g", cat: "과일" },
  { name: "수박", cal: 30, unit: "100g", cat: "과일" },
  { name: "딸기", cal: 30, unit: "100g", cat: "과일" },
  { name: "복숭아", cal: 45, unit: "1개(200g)", cat: "과일" },
  { name: "키위", cal: 55, unit: "1개(100g)", cat: "과일" },
  { name: "배", cal: 50, unit: "1개(300g)", cat: "과일" },
  { name: "망고", cal: 65, unit: "100g", cat: "과일" },
  // 채소
  { name: "당근", cal: 40, unit: "100g", cat: "채소" },
  { name: "브로콜리", cal: 35, unit: "100g", cat: "채소" },
  { name: "양배추", cal: 25, unit: "100g", cat: "채소" },
  { name: "상추", cal: 15, unit: "100g", cat: "채소" },
  { name: "오이", cal: 15, unit: "1개(200g)", cat: "채소" },
  { name: "토마토", cal: 20, unit: "1개(100g)", cat: "채소" },
  { name: "고구마", cal: 130, unit: "1개(150g)", cat: "채소" },
  { name: "감자", cal: 80, unit: "1개(150g)", cat: "채소" },
  { name: "옥수수", cal: 90, unit: "1개(150g)", cat: "채소" },
  // 간식/과자
  { name: "초코파이", cal: 180, unit: "1개", cat: "간식" },
  { name: "빼빼로", cal: 250, unit: "1봉(54g)", cat: "간식" },
  { name: "새우깡", cal: 150, unit: "1봉(45g)", cat: "간식" },
  { name: "포카칩", cal: 220, unit: "1봉(60g)", cat: "간식" },
  { name: "아이스크림(바)", cal: 150, unit: "1개", cat: "간식" },
  { name: "아이스크림(콘)", cal: 220, unit: "1개", cat: "간식" },
  { name: "젤리", cal: 80, unit: "1봉(25g)", cat: "간식" },
  { name: "견과류믹스", cal: 180, unit: "1봉(30g)", cat: "간식" },
  { name: "에너지바", cal: 200, unit: "1개", cat: "간식" },
  { name: "떡(인절미)", cal: 210, unit: "100g", cat: "간식" },
  { name: "팥빙수", cal: 420, unit: "1인분", cat: "간식" },
  { name: "핫초코", cal: 220, unit: "1잔", cat: "간식" },
];

export const OH_DIET: Record<string, {
  emoji: string; color: string; bg: string; label: string;
  kcal: number; type: string; desc: string;
  avoid: string[]; good: string[]; tip: string;
}> = {
  목: {
    emoji: "🌿", color: "#4ade80", bg: "#052e16", label: "목(木)",
    kcal: 1600, type: "채식 체질", desc: "식물성 식품이 잘 맞는 체질",
    avoid: ["기름진 음식", "튀김류", "술"], good: ["채소", "과일", "콩류", "견과류"],
    tip: "아침을 든든히, 저녁을 가볍게 드세요.",
  },
  화: {
    emoji: "🔥", color: "#f97316", bg: "#431407", label: "화(火)",
    kcal: 1800, type: "고단백 체질", desc: "단백질 섭취가 중요한 체질",
    avoid: ["자극적인 음식", "매운 음식", "카페인"], good: ["닭가슴살", "생선", "두부", "달걀"],
    tip: "규칙적인 식사 시간을 지키세요.",
  },
  토: {
    emoji: "🌍", color: "#f59e0b", bg: "#451a03", label: "토(土)",
    kcal: 1700, type: "균형 체질", desc: "균형 잡힌 식단이 중요한 체질",
    avoid: ["밀가루", "단 음식", "야식"], good: ["잡곡밥", "뿌리채소", "호박", "감자"],
    tip: "천천히 씹어 먹는 습관이 중요해요.",
  },
  금: {
    emoji: "⚡", color: "#e5e7eb", bg: "#1c1917", label: "금(金)",
    kcal: 1650, type: "저탄 체질", desc: "탄수화물 조절이 필요한 체질",
    avoid: ["흰 쌀밥", "빵", "당류"], good: ["현미", "브로콜리", "닭고기", "어류"],
    tip: "물을 자주 마시고 식이섬유를 챙기세요.",
  },
  수: {
    emoji: "💧", color: "#93c5fd", bg: "#0c1a35", label: "수(水)",
    kcal: 1750, type: "항산화 체질", desc: "항산화 식품이 잘 맞는 체질",
    avoid: ["짠 음식", "가공식품", "야식"], good: ["등 푸른 생선", "블루베리", "해조류", "견과류"],
    tip: "저녁 7시 이후엔 가볍게 드세요.",
  },
};

export function getOhFromYear(year: number): "목" | "화" | "토" | "금" | "수" {
  const GAN = ["경","신","임","계","갑","을","병","정","무","기"];
  const FROM_GAN: Record<string, "목"|"화"|"토"|"금"|"수"> = {
    갑:"목",을:"목",병:"화",정:"화",무:"토",기:"토",경:"금",신:"금",임:"수",계:"수"
  };
  return FROM_GAN[GAN[(year - 4) % 10]];
}
